### ISSUE TITLE
Next wave doesn't work with turrets placed

### ISSUE THREAD

**Issue by keestim** [daalekz/Firewall#16]
Steps to recreate:
- Place tower down
- Press next wave button

Wave will still happen if there are no towers present when clicking on next wave button.

**Comment by keestim** [comment]
fixed
**However**
functionality of the isolator tower it slightly changed, meaning that the tower can only target enemies after they pass the first nav point on a given map

Is this okay?
@p0isonedpanda 
@LachieWestlake 
@daalekz 
@Flumm3ry

**Comment by daalekz** [comment]
Check with product owner @lachiewestlake to see if this altered functionality sits within our guidelines
